### ISSUE TITLE
Other language support for export logs

### ISSUE THREAD

**Issue by heatherlogan-scottlogic** [ScottLogic/prompt-injection#252]
Currently allows exported logs to print special characters for  hindi/arabic/begali/hebrew/thai by combining individual fonts. 

Due to the glyphs in chinese/korean/japanese fonts it doesn't look like we can combine these fonts together to support characters of all these languages at the same time. 

May need user to specifically select to export in one of these languages so we can switch font on the fly

**Comment by gsproston-scottlogic** [comment]
Relevant issue: https://github.com/diegomura/react-pdf/issues/933

Some possible options are:


- Get user to select the language when they export.
- Use a different PDF renderer.
- Simply output the log in a different format which simply uses unicode characters and not a renderer.
- See if we can leverage this PR https://github.com/diegomura/react-pdf/pull/1833

**Comment by chriswilty** [comment]
In #789 I updated the fonts README with instructions on how to add additional font support, and removed all CJK fonts from our repo.

This issue is now obsolete, closing it.
