### ISSUE TITLE
Prefer immutability in back-end code

### ISSUE THREAD

**Issue by chriswilty** [ScottLogic/prompt-injection#390]
There are a number of functions in the back-end code that consume and modify _as a side effect_ some state objects. 

For example, backend/src/router.ts has a lot of logic for consuming and updating a chatResponse object, and it is tricky to see where in the code this object is being updated, and in what order. The complexity of the router functions is also rather high, which makes it tricky to work out exactly what is happening.

We should attempt to introduce immutability - not necessarily a state reducer-like pattern, but at least returning copies of objects instead of mutating function inputs. This will make it simpler to reason where state changes are happening.

**Comment by pmarsh-scottlogic** [comment]
Full review of `backend/src` methods and what they mutate
- controller/
  - chatController.ts
    - `handleLowLevelChat()`
      - takes and mutates `chatResponse: ChatHttpResponse`
      - calls `chatGptSendMessage()`
    - `handleHigherLevelChat()`
      - takes and mutates `chatResponse: ChatHTTPResponse` - changes `transformedMessage` property
      - takes and mutates `req: OpenAiChatRequest` - adds transformed message to chat history
  - defenceController.ts
  - documentController.ts
  - emailController.ts
  - handleEror.ts
  - healthController.ts
  - modelController.ts
  - resetController.ts
  - systemRoleController.ts
- utils/
  - token.ts
- app.ts
- defaultDefences.ts
- defence.ts
- document.ts
- email.ts
- importMetaUtils.ts
- langchain.ts
- openai.ts
- prmptTemplates.ts
- router.ts
- server.ts

**Comment by pmarsh-scottlogic** [comment]
Created tickets:
- #704

**Comment by gsproston-scottlogic** [comment]
Split into smaller tickets
