### ISSUE TITLE
fix mission information padding

### ISSUE THREAD

**Issue by pmarsh-scottlogic** [ScottLogic/prompt-injection#551]
The button border is being slightly cutoff, specifically on the mission information overlay of level 2.

The container has `overflow-y: auto` on it, which is causing the issue. Can be fixed by adding `padding-bottom: 0.25rem` to the button-area div.

![Image](https://github.com/ScottLogic/prompt-injection/assets/118171430/06706d5c-a26b-45b8-9d71-bd9a79ae2300)

**Comment by dhinrichs-scottlogic** [comment]
Looks good on edge, chrome, and firefox:

![Image](https://github.com/ScottLogic/prompt-injection/assets/125262707/127da891-1442-4de4-b4cc-b22784859cc7)

Moving to done.
