### ISSUE TITLE
Update UI when reset triggered

### ISSUE THREAD

**Issue by smalyon-scottlogic** [ScottLogic/prompt-injection#561]
# Feature Request

## Description
Provide feedback on Level Reset so user can accurately track progress through chat (live or exported).

## Screenshots
![Image](https://github.com/ScottLogic/prompt-injection/assets/105358236/4a32e83e-959f-4a66-8385-16683f394abf)

## Additional context
[Figma](https://www.figma.com/file/dntI3xrEI40De9KDCMCmMI/AI-prompt-injection?type=design&node-id=335-1931&mode=dev)

Disable the button when there's nothing to reset, enable it when there is.
We likely need to use `aria-disabled` here rather than `disabled` so that keyboard-only users can still tab to the button and see that it is disabled.
This shouldn't be an issue, however, as our ThemedButton component already supports this.

Note that this ticket is NOT to update the UI of the buttons, that is done in #573 

Questions: 

- Do we disable the reset button when there's no chat? **- no, no one was too bothered about this, so keep it as is for now.**
- Do we want to have the 'level progress reset' separator? **- yes, it's a nice, clear indicator that the reset has happened.**
- Do we want to show old chat history before the separator? **- no, this gets complicated when considering where and how this old chat history is stored.**

## Acceptance criteria
Do NOT test for updated UI here (aside from disabled look), just functionality.

<s> **GIVEN** chat is empty
**THEN** the "Reset Level" button is disabled
**AND** the "Reset Level" button is focusable

**GIVEN** chat is NOT empty
**THEN** the "Reset Level" button is enabled
**AND** the "Reset Level" button is focusable

**GIVEN** "Reset Level" button enabled
**WHEN** when the user clicks on the button
**THEN** the chat is cleared, and only shows the welcome message from the bot
**AND** emails are cleared
**AND** the button is disabled </s>

**GIVEN** the user clicks reset level button 
**THEN** previous messages (other than welcome msg) are cleared
**AND** "reset level"message  is added to a chat history 

**GIVEN** the user clicks reset level button and exports logs
**THEN** reset level message is shown in logs

**GIVEN** the user clicks reset **progress** button 
**THEN** history is cleared and no "reset" message shown

**Comment by pmarsh-scottlogic** [comment]
Haven't "officially" tested yet but I think I found a bug introduced in this PR

To Reproduce:
- Run app
- Go to sandbox
- enable character limit defence and configure the character limit to, say, 5.
- type a message and observe the character limit kicking in
- reset the level
- enable character limit defence again
- type a long message and observe the character limit NOT kicking in

I think when we re-enable the character limit after reset, it doesn't reconfigure the value to what's in the config box in the front end. And if you step through the backend, it's back to its default value of 280 or whatever.

**Comment by gsproston-scottlogic** [comment]
> Haven't "officially" tested yet (so still worth testing this ticket properly). But I accidentally stumbled into this bug which I'm pretty sure was from this PR:
> 
> ## To Reproduce:
> * Run app
> * Go to sandbox
> * enable character limit defence and configure the character limit to, say, 5.
> * type a message and observe the character limit kicking in
> * reset the level
> * enable character limit defence again
> * type a long message and observe the character limit NOT kicking in
> 
> I think when we re-enable the character limit after reset, it doesn't reconfigure the value to what's in the config box in the front end. And if you step through the backend, it's back to its default value of 280 or whatever.

Might be related to #678 ?

**Comment by pmarsh-scottlogic** [comment]
TESTING:
