### ISSUE TITLE
Level Banner

### ISSUE THREAD

**Issue by smalyon-scottlogic** [ScottLogic/prompt-injection#570]
# Feature Request

## Description
Display information on the current level below the Header.

## Screenshots
![image](https://github.com/ScottLogic/prompt-injection/assets/130466114/ac48f1f1-9d5b-45e8-8ca7-1ff11a21416b)

## Additional context
[Figma](https://www.figma.com/file/dntI3xrEI40De9KDCMCmMI/AI-prompt-injection?type=design&node-id=335-1931&mode=dev)

The banner should only show a short version of the full mission info.

Questions:

- The current banner is clickable. When clicked, it brings up the modal to show the full mission info. Now that the full mission info is shown in the right panel rather than a modal, how do we bring the user back to the full mission info? And should this banner be clickable? **- this is just a UI update ticket, don't change functionality.**

## Acceptance criteria
Ensure that colour contrast passes accessibility standards.
Firefox is good at this. There's an accessibility tab in dev tools where you can see colour contrast warnings.

No functionality changes here, just check the new implementation matches the UI designs.

**Comment by pmarsh-scottlogic** [comment]
Testing:
