### ISSUE TITLE
Update Chat Styles - Bubbles

### ISSUE THREAD

**Issue by smalyon-scottlogic** [ScottLogic/prompt-injection#571]
# Feature Request

## Description
Update chat bubble style as per the current UX design. 

## Screenshots
<img width="444" alt="image" src="https://github.com/ScottLogic/prompt-injection/assets/105358236/e1797da0-7e24-4d45-9f29-31792b331b98">

## Additional context
[Figma](https://www.figma.com/file/dntI3xrEI40De9KDCMCmMI/AI-prompt-injection?type=design&node-id=68-134&mode=dev)

Chat window
    Background - #FFFFFF

Bot bubbles
    background - #E9FEFF
    stroke - #B6ECEF
    border-radius - 0 1rem 1rem 1rem

User bubbles
    background - #009CA5
    stroke - #198B92
    border-radius - 1rem 0  1rem 1rem

Spacing
    1rem between chat bubble and sides of the chat stream, and also between chat bubbles
    1rem padding

<s>No other functional changes here, just UI updates.</s>
To show the original user message in bold, we'll have to change the frontend/backend API a little.
At the moment if the user's message is transformed on the backend, the HTTP response will contain a `transformedMessage` field.
The proposed solution is to now split this into three parts, possibly an object like so:
```typescript
interface TransformedMessage {
  preMessage: string,
  message: string,
  postMessage: string,
}
```
Then the frontend can concatenate the three parts, and bold the `message` part.
This should work for other forms of defences which transform the user message (though we only have one at the moment).

Questions:

- Still need designs for transformed user messages, like what you see when the XML defence is active. **- got this now.**

## Acceptance criteria
Ensure that colour contrast passes accessibility standards.
Firefox is good at this. There's an accessibility tab in dev tools where you can see colour contrast warnings.

Check the following chat bubbles against the UI designs:

- User
- User transformed
- Bot
- Bot error

**Comment by pmarsh-scottlogic** [comment]
![Image](https://github.com/ScottLogic/prompt-injection/assets/118171430/0abe9861-7c0e-42cc-8559-5791b39c3326)



![Image](https://github.com/ScottLogic/prompt-injection/assets/118171430/84db3a64-308f-44c7-b5a2-501db902a30f)
