### ISSUE TITLE
Update Chat Styles - Avatars

### ISSUE THREAD

**Issue by smalyon-scottlogic** [ScottLogic/prompt-injection#572]
# Feature Request

## Description
Add avatars to chat bubbles.

## Screenshots
![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/ea060d00-aff5-49a9-a10f-178fc380540f)

## Additional context
[Figma](https://www.figma.com/file/dntI3xrEI40De9KDCMCmMI/AI-prompt-injection?type=design&node-id=68-134&mode=dev)

The design has a 70px grey circle (#eeeeee) with 15px of spacing on all sides. This might need flexed a little to use REM values.

Questions:
- Still need designs for the user avatars. - Mark has added them to figma!

## Acceptance criteria
Ensure that colour contrast passes accessibility standards.
Firefox is good at this. There's an accessibility tab in dev tools where you can see colour contrast warnings.

- avatar should be enclosed in a circle
- chat bubble should not be shorter than the avatar circle/icon
- chat bubble CAN be taller than the avatar
- spacing on both left and right sides should be equal, and roughly equal to the space vertically between chat bubbles (around 1rem)

**Comment by dhinrichs-scottlogic** [comment]
testing

**Comment by dhinrichs-scottlogic** [comment]
Tested on Edge, Chrome and Firefox, new avatars and chat bubbles are looking good:
![Image](https://github.com/ScottLogic/prompt-injection/assets/125262707/66f12ad6-9494-44ad-8913-53553c50b915)

Moving this to done.
