### ISSUE TITLE
Augment XML Tagging description to mention related defences

### ISSUE THREAD

**Issue by chriswilty** [ScottLogic/prompt-injection#582]
We have removed a few defences from our original wishlist (Random Sequence Enclosure, Sandwich Defence, Instruction Defence) that are similar in purpose to XML Tagging.

It would be nice to mention these in the description of XML Tagging defence, in case users somewhat familiar with prompt injection defences wonder why we haven't included them.

Currently in `frontend/src/Defences.ts`.

Question:

- We may want to add these back in, making sure only one can be active at a time. So if we decide to add these back in, we can remove this issue. TODO: new issue to add more defences which transform the user message.

**Comment by gsproston-scottlogic** [comment]
New issue #703 , we're adding back in RSE and other prompt enclosure defences.
