### ISSUE TITLE
Tackle duplicated toggle defence code

### ISSUE THREAD

**Issue by chriswilty** [ScottLogic/prompt-injection#585]
There are two functions, for setting a defence active and inactive, being drilled all the way down the component hierarchy from MainComponent => MainBody => ControlPanel => DefenceBox => DefenceMechanism, at which point they are combined into a single function that calls one or other of the prop functions depending on the current state of the defence.

This is wasteful as we can pass a single "toggleDefence" prop down the tree which performs the check, instead of checking current active/inactive state at the point of usage. In fact, we also have two duplicated service functions in defenceService.ts, when we only need one - the logic for toggling can be in here.

## AC
Just a refactor, so check app still works, especially toggling defences.

**Comment by pmarsh-scottlogic** [comment]
TESTING:
Yep, toggling stuff on and off works! Tried lots of different orders, and spam clicking and all behaved well :)

Moving to done
