### ISSUE TITLE
Change GPT-4-TURBO preview model to stable model when it is released

### ISSUE THREAD

**Issue by heatherlogan-scottlogic** [ScottLogic/prompt-injection#588]
When openAI release the production ready GPT-4-turbo, 

- [ ] change the model name in enum CHAT_MODELS (currrently "gpt-4-1106-preview")
- [ ] change the langchain models from gpt-4 to gpt-4-turbo 

Reason 
- gpt-4-turbo is 2/3x cheaper than gpt-4 

List of OpenAI models: https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
New models article: https://openai.com/blog/new-models-and-developer-products-announced-at-devday

## AC
Using a new GPT 4 model. Make sure existing models still work (including QA and evaluator LLMs).
Also make sure chatting with the gpt-4-turbo model works.

**Comment by gsproston-scottlogic** [comment]
Adding blocked label until the turbo model is out of preview.
