### ISSUE TITLE
Fix problems with `integration/langchain.test`

### ISSUE THREAD

**Issue by pmarsh-scottlogic** [ScottLogic/prompt-injection#596]
# Testing

## Description
@chriswilty has identified some subtle problems with `integration/langchain.test.ts` and reckons the file could use some attention.

These issues have been identified so far:
- ~~We are assigning the same `mockCall` object to both `mockRetrievalQAChain` and `mockPromptEvalChain`. So in our tests, how can we be sure which chain invoked the call?~~ resolved in #728 
![Image](https://github.com/ScottLogic/prompt-injection/assets/118171430/4286beae-1878-4ab3-bece-cf9c0c853859)

- We are using the any `type` in the definition of `MockDocumentsVector`
  ![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/399f8654-e9ec-4890-add2-23edd40d953a)

- The mocking for RetrievalQAChain, SequentialChain, LLMChain are all just every so slightly different which makes things tricky to read. Possibly there are good reasons that this is done this way
  ![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/f48d0bdb-a26c-4dd8-be11-beead56bee2a)

## AC
Only updating tests, so this can skip the testing step.

**Comment by pmarsh-scottlogic** [comment]
I'm stuck on mocking an object constructor. Toy example of what I want to achieve

```typescript
import { expect, test, jest } from '@jest/globals';
import { OpenAI } from 'langchain/llms/openai';

const initNewOpenAI = // CODE TO MOCK the new OpenAI() constructor

test('test', () => {
	initNewOpenAI.mockReturnValueOnce('hey');

	const output = toTest();

	expect(output).toBe('hey');
	expect(initNewOpenAI).toHaveBeenCalledTimes(1);
});

function MethodToTest() {
	const openAI = new OpenAI({
		modelName: 'davinci',
		temperature: 0,
		openAIApiKey: 'myKey',
	});
	return openAI;
}
```

**Comment by chriswilty** [comment]
Not entirely sure what you are trying to achieve. If you have a function that simply returns the constructed object (as in MethodToTest) and you want to ensure it does indeed return that object... Is that a worthwhile test? Surely better to test that the returned object is _used_ as we expect it to be.

If you really do need to mock a constructor, then you've already done that elsewhere. Something like this?

```
import { expect, jest, test } from '@jest/globals';
import { OpenAI } from 'langchain/llms/openai';

const mockOpenAi = jest.mocked(OpenAI);

jest.mock('langchain/llms/openai', () => ({
  OpenAi: jest.fn(), // as typeof mockOpenAi ??
}));

test('something', () => {
  const mockedOpenAi = jest.mocked(OpenAI);

  FunctionToTest();

  expect(mockedOpenAi).toHaveBeenCalledWith({
    modelName: 'davinci',
    temperature: 0,
    openAIApiKey: 'myKey',
  });
});
```

I've not tried the above, so you might need to correct it a bit... Annoyingly, the jest docs are not great at explaining usage with typescript.
