### ISSUE TITLE
Update level 2 content

### ISSUE THREAD

**Issue by gsproston-scottlogic** [ScottLogic/prompt-injection#618]
# Bug report

## Description
We need to update the level 2 mission info content as we give the user the handbook right away rather than only in level 2 onwards.

## Reproduction steps 
1. Go to level 2
2. Mission info contains a bit about giving the user a handbook.

## Expected behavior
This bit about the handbook should either be in level 1 or removed entirely.

## Screenshots
![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/89b77131-64cc-4b95-a0eb-39fbc1bf7114)

## Additional context
Questions:

- Remove completely or move to level 1? Note that we may want to also point users to the handbook after beating level 1 as that's where the system role is shown. **- Reword the section in level 2.**

## Acceptance criteria
TBD after questions

**Comment by heatherlogan-scottlogic** [comment]
tested 🤞
