### ISSUE TITLE
HTTP requests failing when viewing documents

### ISSUE THREAD

**Issue by asaha-scottlogic** [ScottLogic/prompt-injection#621]
# Bug report

## Description
When viewing documents in sandbox mode, the initial HTTP requests fail. This doesn't stop the documents from being shown, however.

## Reproduction steps 
1. Go to sandbox mode.
2. Open the network tab in browser dev tools (F12).
3. Open the document viewer.
4. See that the request to get the document fails.

## Expected behavior
No failing HTTP requests.

## Screenshots
![image](https://github.com/ScottLogic/prompt-injection/assets/140402149/9325b232-f6ba-4092-9845-e9e0af597952)

## Software (please complete the following information):
 - Browser: Edge

## Additional context
Likely due to the functionality of the package we're using to show documents.

## Acceptance criteria
**WHEN** the user views documents on the sandbox
**THEN** all HTTP requests complete successfully

**Comment by chriswilty** [comment]
This was a case-sensitivity bug, fixed in #904.
