### ISSUE TITLE
Frontend hangs when it doesn't get a chat reply

### ISSUE THREAD

**Issue by gsproston-scottlogic** [ScottLogic/prompt-injection#634]
# Bug report

## Description
If the backend isn't running and the frontend tries to chat to it, then the HTTP request eventually fails. However, the 'send' button stays in a 'loading' state, and the frontend cannot recover.

## Reproduction steps 
1. Run the frontend, DON'T run the backend.
2. Send a chat message.
3. Send button stays loading, even after the request has failed.

## Expected behavior
When the HTTP request fails, show an error in the chat, and allow the user to try again.

## Screenshots
Send button still in loading state, even after the request has failed:

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/c6de6208-33ae-4752-aeaa-7c009232b68d)

## Software (please complete the following information):
 - Browser: Edge

## Acceptance criteria
**WHEN** the user sends a chat message
**THEN** the 'send' button shows loading dots
**AND** the user cannot send another message until a reply is received

**GIVEN** the user has sent a chat message
**WHEN** the backend replies successfully
**THEN** the 'send' button stops showing loading dots
**AND** the user can now send a new message

**GIVEN** the user has sent a chat message
**WHEN** the HTTP requests times out
**THEN** the 'send' button stops showing loading dots
**AND** the user can now send a new message

**Comment by pmarsh-scottlogic** [comment]
testing...
