### ISSUE TITLE
Licence link in footer has weird hover effect

### ISSUE THREAD

**Issue by pmarsh-scottlogic** [ScottLogic/prompt-injection#637]
# Bug report

## Description
Licence link in footer has weird hover effect

## Reproduction steps 
Steps to reproduce the behaviour:
1. Open the app
2. hover over the license link in the footer
3. Observe the underline extending past the license text

## Expected behaviour
The underline is confined to the license text

## Screenshots
![Image](https://github.com/ScottLogic/prompt-injection/assets/118171430/2b832b03-3d06-4f66-b1e6-e3de66643672)

## Software (please complete the following information):
 - Browser: Chrome

## Acceptance criteria
**WHEN** hover over license text
**THEN** underline is confined to license text

**Comment by dhinrichs-scottlogic** [comment]
testing

**Comment by dhinrichs-scottlogic** [comment]
Tested on edge, chrome, and firefox. No more weird hover effect:
![image](https://github.com/ScottLogic/prompt-injection/assets/125262707/3187ca9d-267c-4527-8b22-84e52d5d6012)

Moving this to done.
