### ISSUE TITLE
Chat history exceeds models max context length. 

### ISSUE THREAD

**Issue by heatherlogan-scottlogic** [ScottLogic/prompt-injection#646]
# Bug report

## Description

OpenAI chat completion throws error when chat history exceeds context length. 

## Reproduction steps

Have a long conversation with the bot where the context length exceeds models max context length (e.g. for gpt-3.5-turbo it's 4097, for gpt-4 it is 8192 tokens)

## Expected behavior

There is a function in openai.ts filterChatHistoryByMaxTokens, which should prevent a chat history exceeding the context window. 
It should work by calculating the tokens of each message in chat history and if  the max tokens is reached, trim the older messages until total fits in the context window. 

## Screenshots

![MicrosoftTeams-image](https://github.com/ScottLogic/prompt-injection/assets/118981273/89de2796-ee3c-4c76-a9aa-5a8227e06b6c)

## Software (please complete the following information):

- Browser: [e.g. chrome, safari]

## Additional context

we use this library for counting https://www.npmjs.com/package/openai-chat-tokens which does not support the new tool_call fields which replace the depreciated function_call fields. this may be where the token counting discrepancy occurs.

## Acceptance criteria

**GIVEN** a conversation with the model gets max token length 
**WHEN** I send another message
**THEN** the model is able to respond

**Comment by pmarsh-scottlogic** [comment]
TESTING:
