### ISSUE TITLE
Update hover styles

### ISSUE THREAD

**Issue by chriswilty** [ScottLogic/prompt-injection#647]
# Feature Request

## Description

Update elements with new hover and <s>focus styles</s>. (Update: Focus styles are now done [here](https://github.com/ScottLogic/prompt-injection/issues/722), but can be updated if that ticket is already done)

## Additional context

Following on from #623, we would like to show hover, focused, active and disabled button states in the UI.
Buttons should look different when hovered over.
All focusable elements should have a clearer outline when focused.

Dealer's choice for what colours to use. Just ensure that they meet colour contrast standards for accessibility, and somewhat match the rest of the UI.

## Acceptance criteria

Ensure that colour contrast passes accessibility standards.
Firefox is good at this. There's an accessibility tab in dev tools where you can see colour contrast warnings.

**WHEN** the user hovers over a button in the UI
**THEN** the button style changes colour

**WHEN** the user focuses on an element in the UI
**THEN** the style changes outline colour

**Comment by dhinrichs-scottlogic** [comment]
Additionally, it would be great to get a clearer focus indication on all interactive elements, the black/white outline is hard to see on some buttons and modals.

**Comment by dhinrichs-scottlogic** [comment]
FYI focus styles are being addressed by [this ticket](https://github.com/ScottLogic/prompt-injection/issues/722), but can be updated as needed in this ticket, too

**Comment by jrobb-scottlogic** [comment]
Hi, I'd be interested in working on this issue.

**Comment by pmarsh-scottlogic** [comment]
> Hi, I'd be interested in working on this issue.

Nice one @jrobb-scottlogic! Some things to bear in mind: There's a few different places where buttons are implemented, both as basic html and wrapped within reusable components, so I recommend having a good dig through the interface to find out where they are and what they look like.

Also when adding colours, whack them in the theme.css file in the frontend root :)

Gies us a shout if you have any questions!

**Comment by jrobb-scottlogic** [comment]
Hi guys, I have updated all the buttons with a colour change on hover, but just have one question before I put up a PR! Should this banner (circled in attached image) also have a change on hover? It's technically a button element so I think it would make sense, but thought I would check first.
![image](https://github.com/ScottLogic/prompt-injection/assets/125265795/e7dd011d-44e9-4d4d-83f5-f297a667b1a6)

**Comment by pmarsh-scottlogic** [comment]
> Hi guys, I have updated all the buttons with a colour change on hover, but just have one question before I put up a PR! Should this banner (circled in attached image) also have a change on hover? It's technically a button element so I think it would make sense, but thought I would check first. ![image](https://private-user-images.githubusercontent.com/125265795/296309980-e7dd011d-44e9-4d4d-83f5-f297a667b1a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTM5NjEsIm5iZiI6MTcwNTMxMzY2MSwicGF0aCI6Ii8xMjUyNjU3OTUvMjk2MzA5OTgwLWU3ZGQwMTFkLTQ0ZTktNGQ0ZC04M2Y1LWYyOTdhNjY3YjFhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQxMDE0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmFjYjcyNjVlOWU0MWZiNGU3Njg3MDE5Mjc5OGZmMWUxYTZjYjc1YTRjYzRmMzgyM2M4MWRlNDRkYmEzNDMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XhorhM2CXp1dHYbamgUkaVoHBetmToanjKqB48b4wRc)

@jrobb-scottlogic I would say so yes. Especially given there's nothing much else to indicate that it is clickable!

**Comment by chriswilty** [comment]
@jrobb-scottlogic That's a good question... We've had some back-and-forth about that screen-wide "button which doesn't look like a button", so a hover state (and focused state) change would be nice. However, I am going to say don't implement that here, as we originally had #535 to look at that button. The styling has since changed, but the original problem remains, so we'll tackle it there.

Thanks for the work on this, I'll review now 👌
