### ISSUE TITLE
Sporadically failing UI tests

### ISSUE THREAD

**Issue by chriswilty** [ScottLogic/prompt-injection#658]
# Bug report

## Description

Sporadic test failures, likely due to requests not being cancelled on unmount.

## Reproduction steps

Steps to reproduce the behaviour:

1. Run the DocumentViewBox.test.tsx suite a few times ...
2. Keep running it until you see the "next button is clicked" test fail.

## Expected behaviour

Tests do not fail.

## Screenshots

Below you see the expected change from document 1 to 2 after clicking the Next button, but then it reverts to document 1 again:

![Image](https://github.com/ScottLogic/prompt-injection/assets/15246391/81cf2689-2c73-42af-bbb2-86e3460eb530)

However, it is a bit odd that the log statement occurs more than once, so some additional investigation is needed.

## Software (please complete the following information):

- Browser: None, but uses HappyDom virtual DOM, via vitest tests.

## Additional context

React in _strict mode_ performs a double-render when running in dev mode, which I think might be causing this. If we are not cancelling the original request to fetch the document metas, then they will be set twice, and the second time the document viewer will likely be reset to display the first document. If the Next button click occurs between those two events, and the test runs fast enough, then we have a race condition in which the `expect` might be invoked before or after that second reset event.

## Acceptance criteria

Tests pass consistently.... Not easy to verify!

But no testing needed. tests don't need testing

**Comment by pmarsh-scottlogic** [comment]
difficult to test because the whole suite is skipped! Which, to be fair, solves the sporadic failure problem....

**Comment by chriswilty** [comment]
Hmm, the whole suite is skipped? That sounds wrong :(

@dhinrichs-scottlogic to take a quick look... Thanks!

**Comment by dhinrichs-scottlogic** [comment]
> Hmm, the whole suite is skipped? That sounds wrong :(
> 
> @dhinrichs-scottlogic to take a quick look... Thanks!

was a quick fix we agreed on before Xmas because the DocViewer caused the test to fail. Need to find a workaround.

**Comment by pmarsh-scottlogic** [comment]
## My understanding of the problem

One of the flaky tests is this:
```typescript
test('WHEN the next button is clicked THEN the next document is shown', async () => {
			const { user } = renderDocumentViewBox();
			// wait for header to load
			await screen.findByText(documents[0].filename);

			await user.click(getNextButton());

			expect(
				await screen.findByText(documents[1].filename)
			).toBeInTheDocument();
			expect(
				screen.getByText(`2 out of ${documents.length}`)
			).toBeInTheDocument();
			/* This is sporadically, non_deterministically failing! See #658 for details
			expect(
				await screen.findByText(documents[1].content)
			).toBeInTheDocument();*/
		});
```

**Comment by pmarsh-scottlogic** [comment]
After lots of experimentation with smaller examples, I realised that if we only check that we're passing in the right document array and active document then it works? No idea why. Luckily, these are the crucial things that we need to test, I believe the `pluginRenderers` and `config` are less important.

```typescript
expect(mockDocumentViewer).toHaveBeenLastCalledWith(
	expect.objectContaining({
		activeDocument: getMockedDocumentMetas(documents)[0],
		documents: getMockedDocumentMetas(documents),
	})
);
```
