### ISSUE TITLE
Switch order of input/send and export/reset elements

### ISSUE THREAD

**Issue by dhinrichs-scottlogic** [ScottLogic/prompt-injection#676]
# Feature Request

## Description
Reverse the order of 
- input, send button
and 
- export chat,  reset level buttons

## Screenshots
Desired outcome:
![Image](https://github.com/ScottLogic/prompt-injection/assets/125262707/9bd148f2-c0c8-41e0-a920-09a339e95bf7)

## Additional context
This is helpful for keyboard-only users (going between the chat and the configurations for example), assistive tech, and means the export chat & reset buttons stay in place even as the chat input expands with larger input. 

## Acceptance criteria

**GIVEN** the user chats with the chatbot
**WHEN** they tab through the interactive elements
**THEN** the input and send button come before the export chat and reset level buttons.

**Comment by pmarsh-scottlogic** [comment]
Testing:

![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/c3108829-8451-498b-b001-d827efc83db8)

yep. Flawless. Moving to done
