### ISSUE TITLE
Reset level resets defences, but doesn't update UI

### ISSUE THREAD

**Issue by gsproston-scottlogic** [ScottLogic/prompt-injection#678]
# Bug report

## Description

When the user presses 'reset level', chat and email history is cleared as expected. However, configured defences are also reset on the backend, but this isn't updated on the UI.

## Reproduction steps

Steps to reproduce the behaviour:

1. Go to sandbox mode
2. Configure and turn on some defences
3. Chat with the chatbot
4. Click on the 'reset level' button
5. The configured values are deactivated, but the configuration values are unchanged

## Expected behaviour

Defences are not turned off and are configurations are not cleared.

## Screenshots

Configure defence:

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/3a44bfb8-cc1b-4246-b406-bbf01a2fe6c5)

Reset level:

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/4f0fb79f-f435-4660-ad7a-3e7e7857ba80)

Turn defences back on:

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/85e35fb2-9749-412e-9c8e-0cbe6cf1ec50)

## Software (please complete the following information):

- Browser: Edge

## Additional context

Also for this ticket, add a confirmation modal after clicking the 'reset level' button.

## Acceptance criteria

**WHEN** the user clicks 'reset level'
**THEN** a confirmation modal is shown

**GIVEN** the user has turned on and configured some defences
**WHEN** the user clicks 'reset level'
**THEN** the defences remain active and configured

**Comment by gsproston-scottlogic** [comment]
Add confirmation modal. 
Also reword modal for 'reset progress' button.

**Comment by pmarsh-scottlogic** [comment]
TESTING:
After resetting the level, the defences stay active and the configuration values remain the same
![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/b38fab0f-843a-456c-a6c2-d88b5e7cfa5f)

moving to done
