### ISSUE TITLE
Blank error message shown after switching levels

### ISSUE THREAD

**Issue by heatherlogan-scottlogic** [ScottLogic/prompt-injection#685]
# Bug report

## Description

Blank error message shown after welcome

## Reproduction steps

Steps to reproduce the behaviour:

go on a level, say hey, switch to another level then back 
a blank error bubble is shown  

## Screenshots

![Image](https://github.com/ScottLogic/prompt-injection/assets/118981273/7b1342f3-2432-47f3-90ae-76c99c9141f1)

## Software (please complete the following information):

- Browser: [e.g. chrome, safari]

## Acceptance criteria

**GIVEN** the user switches levels
**WHEN** they switch back
**THEN** the chat history should be expected

**Comment by pmarsh-scottlogic** [comment]
Testing:
