### ISSUE TITLE
Blocked messages not showing correctly in the exported log

### ISSUE THREAD

**Issue by gsproston-scottlogic** [ScottLogic/prompt-injection#700]
# Bug report

## Description

Replies from the chatbot which are blocked are shown on the right side of the log, rather than the left.

## Reproduction steps

Steps to reproduce the behaviour:

1. Go to sandbox mode
2. Activate a defence, for example character limit
3. Trigger the defence with a long message
4. Export the log

## Expected behaviour

The blocked bot message should be on the left.

## Screenshots

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/6bc618e7-11ee-447e-923c-652957631586)

## Software (please complete the following information):

- Browser: Edge

## Acceptance criteria

**GIVEN** the chat history contains a blocked bot reply
**WHEN** the log is exported
**THEN** the blocked reply is shown on the left

**Comment by pmarsh-scottlogic** [comment]
Looks good for character limit, input filtering, output filtering and prompt evaluation
![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/628c6cde-6e03-4f56-9fa3-bf2d153b25a4)
![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/c891a406-2e1c-4859-b060-4708a480292d)
![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/5c048985-2955-4c0d-b7cd-5aeaa3fbfe6f)
