### ISSUE TITLE
Add Random sequence enclosure defence back in 

### ISSUE THREAD

**Issue by heatherlogan-scottlogic** [ScottLogic/prompt-injection#703]
# Feature Request

## Description

Add the random sequence enclosure defence back in. 
Configure toggles so that random sequence enclosure and XML tagging cannot be active at the same time. 
Options 
<s>1. disable other toggle while defence is active
2. automatically toggle the other off when one is turned on</s>

Make it clear to user that they cannot have two defences active at the same time
<s>1. if we go with option 1) could have a info message on hovering the disabled toggle
2. include the reason in the defence description</s>

Have a section like "prompt enclosure" that encapsulates both defences 
Use radio buttons to switch between so two cannot be active at the same time. 
Have the configurations for the defence change when radio button is selected. 

## Screenshots

If applicable, add screenshots to help explain your request.

## Additional context

Code was removed here: https://github.com/ScottLogic/prompt-injection/commit/24bb21675667147633e03f1785b679d5af80f493

## Acceptance criteria

**GIVEN** user activates RANDOM SEQUENCE ENCLOSURE defence
**WHEN** they write a message
**THEN** a transformed message is sent to the bot 

**GIVEN** user has clicked RANDOM SEQUENCE ENCLOSURE radio button
**THEN** the configurations are shown below 
**AND** they cannot activate XML TAGGING

**GIVEN** user has activated XML TAGGING
**THEN** they configurations are shown below
**AND** they cannot activate RANDOM SEQUENCE ENCLOSURE

**Comment by heatherlogan-scottlogic** [comment]
![Image](https://github.com/ScottLogic/prompt-injection/assets/118981273/8238efa3-b129-48cd-9b19-0858e72b0d28)

**Comment by kclark-scottlogic** [comment]
Testing:

![Image](https://github.com/ScottLogic/prompt-injection/assets/60878313/c483e600-9e93-4bc8-b247-5f9cc2752539)

As seen in screenshot there is toggle buttons for the settings and only one can be selected at one time, The one that is selected is put into the chat

**Comment by kclark-scottlogic** [comment]
Bouncing back just for abit of rewording of descriptions. Nothing wrong with functionality

**Comment by dhinrichs-scottlogic** [comment]
Found an accessibility issue: The radio buttons should be linked to each other. 
Currently, they are individual buttons, that programmatically have nothing to do with each other.  As a result, the Screen Reader announcement is: "XML Tagging Radio Button one of one" instead of "XML Tagging Radio Button two of three".
