### ISSUE TITLE
Clear defences when resetting progress

### ISSUE THREAD

**Issue by gsproston-scottlogic** [ScottLogic/prompt-injection#710]
# Feature Request

## Description

When the user clicks 'reset progress' and confirms, then all defences should be reset across all levels, including sandbox.

## Screenshots

Configure defence:

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/b4004c89-0e20-48cb-af44-7341fe28be62)

After resetting progress:

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/183e9440-b4de-4cdb-8441-0be41798680f)

## Additional context

Also need to reword the confirmation modal to be clear that defences will be cleared.

## Acceptance criteria

**WHEN** the user clicks 'reset progress' button
**THEN** the confirmation modal explains that defences will be reset

**GIVEN** the user has activated and configured some defences
**WHEN** the user clicks 'reset progress' button and confirms
**THEN** all defences are reset on level 3
**AND** all defences are reset on sandbox

**Comment by kclark-scottlogic** [comment]
Testing: When I set all the defenses in sandbox I am no longer able to select the "reset progress" button @heatherlogan-scottlogic

**Comment by kclark-scottlogic** [comment]
Bug above turned out not to be related to 710 and was fixed already so moved back into testing
