### ISSUE TITLE
Show error in the handbook if we fail to get system roles

### ISSUE THREAD

**Issue by gsproston-scottlogic** [ScottLogic/prompt-injection#713]
# Bug report

## Description

Show an error on the 'system role' page if we fail to get the system roles from the backend.

## Reproduction steps

Steps to reproduce the behaviour:

1. Don't run the backend
2. Enter story mode (not sandbox)
3. Open the handbook
4. Go to the 'system role' page

## Expected behaviour

Show an error saying we failed to retrieve the system roles.

## Screenshots

Current:

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/e4965860-91b6-4da7-863f-3e9ce4219505)

Figma design:

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/9800315a-aca8-4243-ada0-da4ef2847dc6)

## Software (please complete the following information):

- Browser: Edge

## Additional context

[Figma](https://www.figma.com/file/dntI3xrEI40De9KDCMCmMI/AI-prompt-injection?type=design&node-id=765-1945&mode=dev).

Questions:

- We could hard code system roles on the frontend, to avoid having to get them from the backend. The only trouble here would be keeping them in sync if they were ever to change. **- don't bother with this. Too much to worry about for such a niche issue.**

## Acceptance criteria

**GIVEN** the backend isn't running
**WHEN** the handbook is opened to the system role page
**THEN** an error is shown

**Comment by dcottle-scottlogic** [comment]
Hey would I be possible for me to work on this issue?

**Comment by gsproston-scottlogic** [comment]
Hi @dcottle-scottlogic , that'd be great thanks, I'll assign you to this now.
