### ISSUE TITLE
Improve Focus Styles

### ISSUE THREAD

**Issue by dhinrichs-scottlogic** [ScottLogic/prompt-injection#722]
# Feature Request

## Description
Currently, the keyboard focus is not always easy to see in the default focus styles. 
Adjust the focus styles so that they're easier to see and fit into our colour scheme.

For all elements set outline: 3px solid #2bb3bb (--accent-border-colour).
For elements with a teal background (or where the --accent-border-colour is not as easy to see), add a 1px white border on focus, so that the accent border colour is visible.

## Screenshots
**Default focus:**
![Image](https://github.com/ScottLogic/prompt-injection/assets/125262707/012b56a8-28f8-4fbc-8bbd-995b4f6a2782)

**Desired Outcome:**
![Image](https://github.com/ScottLogic/prompt-injection/assets/125262707/b0ea1282-7bea-443c-b7ba-7bedc58ab0bc)

## Acceptance criteria

**GIVEN** user tab through the app
**WHEN** they focus on an element
**THEN** it's easy to see visually which element they're on

**Comment by chriswilty** [comment]
Interesting... Chat bubbles can be focused, is that so their content can be read out again, instead of just the first time they appear? This project is really educational, it's forcing me to think about UIs in a whole different way!
