### ISSUE TITLE
Redesign the left panel

### ISSUE THREAD

**Issue by gsproston-scottlogic** [ScottLogic/prompt-injection#723]
# Feature Request

## Description
[update: some of the configs have been redesigned for accessibility, here's the design updates that could be made to update the rest] 

- Make scrollbar invisible so that it doesn't shift the content as it appears
- Ensure <textarea>s and <input type=number> have sufficient colour contrast, even when readOnly
- <s>Give `<summary>` buttons the info icon (make sure it's aria-hidden) and apply the same button across all configurations</s> instead: replace the "i" icon button in the model configuration with the "Detail" button that the defence configurations have
- Give the model selection its own visibly distinct area (e.g. a fieldset like the others?)
- Adjust the model configurations that have sliders (e.g. Model Temperature, Top P ...) so that they look like the other configurations (e.g. Prompt Evaluation LLM). it's already a <fieldset>, just needs the same border, headings and buttons. 

## Screenshot of suggested changes:
![image](https://github.com/ScottLogic/prompt-injection/assets/125262707/81508184-7c31-48ba-bb5f-c552e6777ed7)

## Acceptance criteria
- Given a user is in sandbox mode

**Scroll bar:**
- When they expand multiple configurations so that scrolling is necessary
- Then  the sidepanel width does not shrink to make space for the scrollbar (either because the scroll is invisible, or because the space is adjusted to take the scrollbar into account)

**Colour Contrast:**
- When the input fields of the configurations are in read only
- Then the colour contrast between the background and the text of the input element is at least 4.5:1

**Model Selection area**
- When the user interacts with the Model Selection are
- Then the area is visually programmatically grouped together (you can see the controls belong together and a screen reader will tell you the controls are grouped by announcing something like "Model Selection, grouping")

**Model Configurations (e.g. Model Temperature, Top P, all of those with slider controls)**
- When the user interacts with the Model Configurations 
- Then the area is visually programmatically grouped together (you can see the controls belong together and a screen reader will tell you the controls are grouped by announcing something like "Model Temperature, grouping") 
AND
- The button to expand the section for more information (currently an "i" icon) looks identical to the "Details" button in the Defence Configurations

**Comment by chriswilty** [comment]
@dhinrichs-scottlogic to update with latest state and ideas for improvement / UX input.

**Comment by chriswilty** [comment]
Like these 👍 

Do we want to change slider colour to the theme teal at the same time? It's odd that they're the only green controls.

**Comment by gsproston-scottlogic** [comment]
> Like these 👍
> 
> Do we want to change slider colour to the theme teal at the same time? It's odd that they're the only green controls.

yes, I like this 🎨

**Comment by AAloshine-scottlogic** [comment]
do you mind if i take on this ticket?

**Comment by chriswilty** [comment]
I'm still thinking about the Details "buttons", and how the native element has an arrow visually indicating its current state. I think that would be clearer than an info icon.

![image](https://github.com/ScottLogic/prompt-injection/assets/15246391/dfd6aa04-1b89-4377-9ecd-19670fcbdf1e)
![image](https://github.com/ScottLogic/prompt-injection/assets/15246391/6c2ad207-55b8-4eb8-97c3-bf33b0d9e44e)

**Comment by chriswilty** [comment]
Doro has indicated that screen readers can output some seriously long-winded description of the default arrows of `<details>` elements, so we might instead want to use our own unicode chars wrapped in an aria-ignored span.

![unicode_arrows-1445684508](https://github.com/ScottLogic/prompt-injection/assets/15246391/6591b3a6-6610-40b8-99c8-6578c201135c)

**Comment by dhinrichs-scottlogic** [comment]
- I'm not a huge fan of conveying meaning through icons as they can be difficult to understand and have different meanings between cultures. 
- We could use text, but that would give screen reader users confusing info for the summary button: "Expand, button, collapsed", "Collapse, button, expanded".
- This is why I opted for the outset vs inset border as this is closer to how we visually perceive objects in the natural world (e.g. a physical button in the real world that isn't pressed would stand out from the background, like an outset border, whereas a button pressed in would look pushed into the background, like an inset border) and therefore a bit more intuitive. If it's too difficult to see the difference, maybe could adjust the colour or shading to make it more clear. 
- If folks still don't like inset/outset borders and would rather have an icon, then that's alright, we can do that, I just have one more thought on this: The triangle as an indication between collapsed and expanded is not very clear, as the difference is only a few degrees of rotation, so can we make it an arrow instead?

**Comment by chriswilty** [comment]
@dhinrichs-scottlogic I just thought keeping it as close to the native `<details>` element as possible would be a good thing.

**Comment by dhinrichs-scottlogic** [comment]
> @dhinrichs-scottlogic I just thought keeping it as close to the native `<details>` element as possible would be a good thing.

You'd think so, but for our Defence Configuration <details> element we're getting (NVDA on Firefox): 
"Filled right pointing small triangle Defence Configuration button collapsed. 
If you remove the triangle element, like I did for the Details Button within the configurations, NVDA doesn't read out the triangle description, so you only get: "Details Button, collapsed". 
If I hadn't removed the default triangle, it would be: "Filled right pointing small triangle details button collapsed".

I'd rather go with what would work best in practice, rather than going with the default.

**Comment by kclark-scottlogic** [comment]
Bouncing back to review as noticed in edge and chrome, Scroll bar makes panel space smaller while in firefox scroll bar is invisible

**Comment by dhinrichs-scottlogic** [comment]
closing since work has been done
