### ISSUE TITLE
Standardise blocked message responses

### ISSUE THREAD

**Issue by pmarsh-scottlogic** [ScottLogic/prompt-injection#731]
# Feature Request

## Description

Have different blocked messages be more consistent. I think when the user's message is blocked, we should have some standard format for the response.

## Screenshots

Here's how each blocked message looks by defence type.

### Character limit
![Image](https://github.com/ScottLogic/prompt-injection/assets/118171430/cee65f3d-45f4-4168-a79c-17ffd9161426)

### Input filtering
![Image](https://github.com/ScottLogic/prompt-injection/assets/118171430/55ee7052-6e09-412f-ae2c-18f56f0d7003)

### Output filtering
![Image](https://github.com/ScottLogic/prompt-injection/assets/118171430/7c04eadc-1ca6-4adc-a1c2-fbfcc556c18a)

### Prompt Evaluation
![Image](https://github.com/ScottLogic/prompt-injection/assets/118171430/ceb263f8-99ab-4cdc-9d42-60062fdbf470)

## Acceptance criteria

**GIVEN** a defence is active that could block a user message
**WHEN** a user's message is blocked
**THEN** the output follows some kind of set format

I reckon the format should be
"Message Blocked: [more specific info]"

So for each defence:
- "Message Blocked: Input exceeded character limit."
- "Message Blocked: I cannot answer questions about 'secret project'."
- "Message Blocked: My response was blocked as it contained a restricted word/phrase.
- "Message Blocked: The prompt evaluation LLM detected a malicious input."

**Comment by Ben-EJ** [comment]
Mind if I give this a go : )

**Comment by gsproston-scottlogic** [comment]
> Mind if I give this a go : )

Hi Ben, that'd be great thanks 😄 I've just assigned you to this issue.

**Comment by Ben-EJ** [comment]
Have created a PR for this issue: https://github.com/ScottLogic/prompt-injection/pull/747

**Comment by pmarsh-scottlogic** [comment]
Merged :) Thanks @Ben-EJ!
