### ISSUE TITLE
Transformed messages not showing correctly 

### ISSUE THREAD

**Issue by gsproston-scottlogic** [ScottLogic/prompt-injection#741]
# Bug report

## Description

After refreshing the page or switching levels, the user's transformed messages don't show correctly. The original message is no longer bold and the info message isn't shown. 

## Reproduction steps

Steps to reproduce the behaviour:

1. Go to sandbox mode
2. Activate XML tagging
3. Send a chat message
4. Wait for the reply
5. See that there's an info message, and the original message is bold within the transformed message
6. Refresh the page OR switch levels
7. No info message and the original message is not bold.

## Expected behaviour

The transformed message should contain the original message in bold, and should be below an info message saying the original message has been transformed.

## Screenshots

Before refreshing or switching level:

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/8f4d95fa-dadb-476c-8c56-16dae529bfb7)

After:

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/081ce6ce-f5a7-47a0-a14d-d516683bd8cd)

## Software (please complete the following information):

- Browser: Edge

## Acceptance criteria

**GIVEN** a message has been transformed
**WHEN** the page is refreshed
**THEN** the transformed message contains the original message **in bold**
**AND** there is still an info message above the transformed message explaining that the original message has been transformed

**GIVEN** a message has been transformed
**WHEN** the user switches level and then back to the original level
**THEN** the transformed message contains the original message **in bold**
**AND** there is still an info message above the transformed message explaining that the original message has been transformed

**Comment by pmarsh-scottlogic** [comment]
# getChatHistory

```typescript
function getChatHistory {
  // get chatHistory from backend
  // for each message in retrieved chat history (type `ChatHistoryMessage`), convert it to type `ChatMessage` and add it to `chatMessages` array
  return chatMessages
}
```
this could be refactored to use a .filter (to filter out the messages of type `SYSTEM` and `FUNCTION_CALL`) and a .map to convert each message from type `ChatHistoryMessage` to `ChatMessage`. Also these could have more distinct names.

`getChatHistory` is called by `setNewLevel`, which gets the chat history and then updates the frontend `messages` state variable.

`setNewLevel` is only called in place: in a useEffect.
```typescript
	useEffect(() => {
		void setNewLevel(currentLevel);
	}, [currentLevel]);
```

**Comment by pmarsh-scottlogic** [comment]
when we send a chat message with xml tagging we want
- The info message "you message has been transformed blah blah" to be added to the session history.
- The backend to create, store and return the transformed message in the correct format [with the fancy type]
- The backend to return this info message and transformed message when requested by frontend's `getChatHistory(...)`
- The frontend to display those things correctly

**Comment by pmarsh-scottlogic** [comment]
So, at the minute when the user sends a chat message with xml tagging, it gets to the backend chatController method `handleHigherLevelChat()`. At this point, we create the transformed message, first as type 
```typescript
interface TransformedChatMessage {
	preMessage: string;
	message: string;
	postMessage: string;
	transformationName: string;
}
```

**Comment by pmarsh-scottlogic** [comment]
There's overlap with #705, so I won't work on this until that is done. BLOCKED
