### ISSUE TITLE
Update focus style for Prompt Enclosure radio buttons

### ISSUE THREAD

**Issue by pmarsh-scottlogic** [ScottLogic/prompt-injection#754]
# Feature Request

## Description

Have the radio button focus match the nice thick blue indicators that are on the other elements!

## Screenshots

Here's what we have
![Image](https://github.com/ScottLogic/prompt-injection/assets/118171430/b53f73d5-0c95-4309-8988-9a8947f1fadf)

We should have something more like this
![Image](https://github.com/ScottLogic/prompt-injection/assets/118171430/cdf5cb91-8cb7-41f9-bb50-feec462c699c)

## Acceptance criteria

**WHEN** A radio button in the Prompt Enclosure defence settings is focused
**THEN** It should have a nice thick blue focus indicator, similar in appearance to the focus indicators on other elements

**Comment by chriswilty** [comment]
I noted that at zoom levels above 100%, the focus ring is a little cropped, on Firefox browser. Possibly needs a little more padding.
