### ISSUE TITLE
Various visual bugs

### ISSUE THREAD

**Issue by gsproston-scottlogic** [ScottLogic/prompt-injection#757]
# Bug report

## Description

A few visual bugs that _might_ have been caused by #732 .

- [x] Sandbox handbook scrolls into nothing.
- [x] Small close button on some overlays.
- [x] Unexpected document viewer disabled button styling (blue border).

## Screenshots

Handbook scroll:

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/9951baa5-8e26-4cac-ad97-4c3664d14ca3)

Small close button:

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/7cd58d32-f14f-4271-81c7-e3dfbaecf382)

Document viewer button:

![image](https://github.com/ScottLogic/prompt-injection/assets/103250539/7edd14ae-2722-4a6a-8743-0de3929465f7)

## Software (please complete the following information):

- Browser: Edge

## Additional context

- Happy to have these as separate issues.

## Acceptance criteria

**GIVEN** the user is on sandbox
**AND** has opened the handbook
**WHEN** the user scrolls down through the attacks
**THEN** all the attacks are shown 

**GIVEN** the 'getting started' overlay is open
**THEN** the close button is sized correctly

**GIVEN** the document viewer is open
**AND** the first document is shown
**THEN** the disabled "previous" button does not have a blue border.

**Comment by pmarsh-scottlogic** [comment]
# When scroll was working

**"handbook-overlay" div**
![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/7878a83b-ac1b-4b8b-898d-ca87619500b9)
- fixed hwight

**"content" div**
![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/86029676-205d-4fde-8e99-7ff9b0dfa6bf)
- overflow-y: auto

**"handbook-page" article**
![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/b1bb47dc-03da-46ee-9ec8-62f948cfee59)
as tall as the the text content within
