### ISSUE TITLE
Prompt Enclosure config resets to none when refresh or switch level

### ISSUE THREAD

**Issue by pmarsh-scottlogic** [ScottLogic/prompt-injection#762]
# Bug report

## Description

In sandbox, when you select a prompt enclosure defence option, then refresh or switch to a different level and back to sandbox you'll see that the none option is now selected and the message is not being transformed

## Reproduction steps

Steps to reproduce the behaviour:

1. open the app and go to sandbox
2. open Defence Configuration panel, then the Prompt Enclosure panel, and select an option other than `none`
3. configure  the pre-prompt if you like.
4. refresh the page OR navigate to a different level and back to sandbox
5. open Defence Configuration panel, then the Prompt Enclosure panel
6. Observe that the `none` option is now selected
7. Send a message
8. Observe that the message is not transformed
9. Re-select the option you selected before
10. Observe that you are not allowed to configure the prompt any more (until you select a different option and select the first one again). Also there is an info message in the chat that you have disabled the option you just selected

## Expected behaviour

When you refresh or switch to a different level and back to sandbox, the selected Prompt Enclosure option should remain selected, and the user's message should still get transformed

## Screenshots
configure the prompt enclosure defence
![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/f1b6b871-fdcb-44a7-98f7-3635010ab585)

after refresh
![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/25a56c1b-63fb-47a6-b045-c67079c8b8bc)

After reselecting the original option
![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/91fd6154-08be-442c-acea-ad44e8638569)
![image](https://github.com/ScottLogic/prompt-injection/assets/118171430/c345abb1-904e-4674-9387-bfe7a8ed09cb)

## Software (please complete the following information):

- Browser: chrome

## Additional context

Probably related to #741 and #744 

## Acceptance criteria

**GIVEN** In sandbox and a Prompt Enclosure option is selected
**WHEN** refresh page or switch to a different level then back to sandbox
**THEN** That same Prompt Enclosure option remains selected.
**AND** Further messages get transformed
**AND** the prompt config is editable

**Comment by gsproston-scottlogic** [comment]
should be fixed in #753

**Comment by pmarsh-scottlogic** [comment]
It was fixed! I will close the issue
