### ISSUE TITLE
Give every modal a header with title and close button

### ISSUE THREAD

**Issue by dhinrichs-scottlogic** [ScottLogic/prompt-injection#782]
# Feature Request

## Description
- Give every modal a header with heading and close button ("close" text and an X icon)
- Adjust all pop up modals (Welcome modal, Mission Information, Handbook and Document viewer)
- Replace the modal close button (curently an X at the top right corner) with a button with the text "Close" and an  X icon. Add aria-hidden to the icon. Remove tooltips and aria-labels from the close button.  

## Acceptance criteria

**GIVEN** A modal is open
**THEN there is a header with title and close button**

**WHEN** A visual user looks for the close button
**THEN** they see a "Close" button and an X icon with a round border, 

**WHEN** A screen reader user tabs to the close button
**THEN** they hear "Close, button" but do not hear the icon announced.

### Wireframes:
Welcome modal:
![image](https://github.com/ScottLogic/prompt-injection/assets/125262707/ed3889b3-d4b1-4272-97f6-625e8958312d)
Mission Info:
![image](https://github.com/ScottLogic/prompt-injection/assets/125262707/a19b9e71-5e3e-4fcb-9ba1-883b4040f3f0)
Document Viewer:
![image](https://github.com/ScottLogic/prompt-injection/assets/125262707/ee73cf52-c1bb-41f3-b66b-80cacc5fa5bb)
Handbook:
![image](https://github.com/ScottLogic/prompt-injection/assets/125262707/82813e79-c31e-41af-93b7-788ff1a97dc5)

## Notes:
Who knew close buttons can be so controversial 😄! Here's some interesting articles on this: 
https://www.htmhell.dev/20-close-buttons/
https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html

**Comment by m4rkwallace-SL** [comment]
Added these to the figma file 

<img width="651" alt="Screenshot 2024-01-22 at 09 51 55" src="https://github.com/ScottLogic/prompt-injection/assets/105358236/fc7721ce-9da0-477f-b62e-bf15faf7040f">
<img width="653" alt="Screenshot 2024-01-22 at 09 51 17" src="https://github.com/ScottLogic/prompt-injection/assets/105358236/4e080c3f-b437-4bf5-bdfe-0a1513cb5557">

**Comment by dhinrichs-scottlogic** [comment]
During discussion, we anticipated an issue with the scrolling of the modals interfering with the close button. One idea to work around that was to give the modals headers, with a heading and a close button. Headings would be a great addition to the modals. 
![image](https://github.com/ScottLogic/prompt-injection/assets/125262707/c6f9cca9-0e07-4862-ac8d-f74774b76b81)
