### ISSUE TITLE
Too many options to close the same modal

### ISSUE THREAD

**Issue by dhinrichs-scottlogic** [ScottLogic/prompt-injection#786]
# Feature Request

## Description
Many of our modals can be dismissed with the close button at the top right, as well as an "Okay" or "Cancel" button.
It can be confusing to have multiple ways to dismiss the same modal, so this needs to be redesigned

**Comment by chriswilty** [comment]
@dhinrichs-scottlogic Can this go into one of your milestones, so we don't lose track of it?

**Comment by chriswilty** [comment]
Will not fix, as this is _almost_ redundant following the multi-page modal redesign (#578). The "reset" modals still have two close buttons, but it's open to debate whether or not it's a bad thing. As it stands, all story modals have the same look'n'feel so it feels worse to remove the top-right close button for just these two modals.
