### ISSUE TITLE
Network usage investigation

### ISSUE THREAD

**Issue by pmarsh-scottlogic** [ScottLogic/prompt-injection#792]
Interact with different parts of the app. Make note of network calls and identify where we could cut down on number of calls, and the content contained within. Can we combine several calls into one? Is any of the information not needed?

Write a list of all the improvements that could be made, and prioritise in order of what will make the most impact. Write tickets to implement.

AC:
No code changes, therefore no testing needed.

**Comment by pmarsh-scottlogic** [comment]
## Refresh
Here's what happens if I refresh on level 1:
- `health/` always returns with 200 (if the backend is up).
- `email/get?level=0` returns all the sent emails in the session for given level.
- `openai/history?level=0` returns the chat history in the session for given level.
- `defence/status?level=0` returns the defences as configured for given level.
- `openai/validModels` returns all the available models from openAI for the api key configured in the backend.
- `systemRoles/` returns the default system role values for levels 1, 2 and 3.

**Comment by pmarsh-scottlogic** [comment]
Tip: use `npm run preview` to run not in strict mode (stop the double renders)

**Comment by pmarsh-scottlogic** [comment]
Question:
- Reducing api calls is hard, because there's a balance of minimising calls while also minimising the amount of stuff we're storing in the frontend. At the extreme, we could do one api call on loading the app, and then exactly one further API call for each distinct interaction the the user makes. But that would require the client to hold information about every level at once, therefore most of the stored information will be irrelevant at any point. Therefore: Is there a good philosophy of how far to take it, or should I just use common sense?

**Comment by chriswilty** [comment]
Great writeup 🏆

I see you'd already spotted the double message on Activating a defence - the second one adds an info message stating the defence had been activated, like

> Hey backend, activate this defence for me would ya?
> "Sure, done!"
> Hey backend, that defence is now active ok?
> "Erm ... yeah I know mate" 👀 

Removing all the redundant "add history message" calls from the UI will require some working out, presumably tackling them one at a time until no more remain, then squishing the backend endpoint and frontend service. The ones that are conditionally sent in ChatBox component in the (colossal) processChatResponse function will require some careful work, though probably the main effort will be ensuring all (successful) responses contain the new messages to add to the chat panel, as some of those requests don't appear to have any response body.

The avatars are fine, they are requested first time they are needed then the browser (and actually CloudFront as well, in remote deployment) will cache them.

Reset Progress is an interesting one. We don't expect it very often, so 25K of config data seems acceptable, but ... do we really need it all? Can we not (or do we not already) fetch the level config when we switch levels?

And finally, we could of course cache _everything_ in the UI as you suggest, but when a user has been chatting to the bot for a while, chat data are likely to grow significantly. As you say, it's a trade-off between using browser memory (or local storage) and sending the same data over the network more than once. We are storing all this data server-side anyway, so it's (computationally) cheap for the backend to send what the UI needs on demand, e.g. when a user switches level or refreshes the page. We don't anticipate users doing that very often, so it feels like an acceptable trade-off.

**Comment by pmarsh-scottlogic** [comment]
Tickets made and prioritised, so I'm marking this as done
