### ISSUE TITLE
Can't run the app due to OpenAI API's quota

### ISSUE THREAD

**Issue by cfisher-scottlogic** [ScottLogic/prompt-injection#887]
# Bug report

## Description

> Error: Error initializing document vectors: InsufficientQuotaError: You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.

I received the above error when attempting to run the app locally for the first time.

## Reproduction steps

Steps to reproduce the behaviour:

1. Follow setup steps in _[Setup Local Environment](https://github.com/ScottLogic/prompt-injection?tab=readme-ov-file#setup-local-environment)_
2. `npm run build`
3. `npm start`

## Expected behaviour

The application to launch.

## Additional context

I mistakenly assumed OpenAI had a free tier of API usage. This doesn't appear to be the case, which would make sense as it's an expensive tool to use. But this restriction places an unintentional (and unavoidable) paywall on running and using _SpyLogic_, so I think a disclaimer in the `README` would be useful (even though this disclaimer might be obvious to some).

**Comment by pmarsh-scottlogic** [comment]
Thanks @cfisher-scottlogic! We were also under the impression that free accounts some limited amount of use.

After further investigation, I've found that when you create an OpenAI account (whether to access the API or use their own GPT interface), you are given some number of free credits. For me it was $5;. However that credit expires after an allotted time, which is what I expect has happened to you. I do not know if new accounts still get free credit on creation (will find out)
